# Site settings
title: Dubai
client:
  name: Dubai
  link: "https://www.visitdubai.com/de"

core-se-link: https://www.secretescapes.de
description: >
  Wenn man von Luxus spricht, denken viele als Erstes an Dubai. Die Hauptstadt des gleichnamigen Emirats ist globaler Vorreiter, wenn es um Architektur, Shopping oder Komfort der höchsten Klasse geht. Finden Sie heraus, wo Ihr Lieblingsstrand ist, shoppen Sie sich durch die Weltgeschichte.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2020/dubai" # the subpath of your site, e.g. /blog/
img:     "/de/2020/dubai/_assets/img"
css:     "/de/2020/dubai/_assets/css"
js:      "/de/2020/dubai/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
